[project]
name = "visualstat-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.12",
    "matplotlib>=3.9.4",
    "pydantic>=2.11.7",
    "scipy>=1.13.1",
    "uvicorn>=0.34.3",
]
